// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUX0RbfSEjf-o9U8KqkLQo3h0kg6DNXw',
    appId: '1:579482424180:web:81335106ece73b1c4e1221',
    messagingSenderId: '579482424180',
    projectId: 'tfm-control',
    authDomain: 'tfm-control.firebaseapp.com',
    storageBucket: 'tfm-control.appspot.com',
    measurementId: 'G-R23DG1CM93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahO4pec_sologlMfzJJyrq0e33oCa7xY',
    appId: '1:579482424180:android:ee81ef355339d0814e1221',
    messagingSenderId: '579482424180',
    projectId: 'tfm-control',
    storageBucket: 'tfm-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGctIM4YwdCknA2kMuSa4F8xeY_Osegg',
    appId: '1:579482424180:ios:2e2afae2a4e487584e1221',
    messagingSenderId: '579482424180',
    projectId: 'tfm-control',
    storageBucket: 'tfm-control.appspot.com',
    iosBundleId: 'com.example.tfmControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHGctIM4YwdCknA2kMuSa4F8xeY_Osegg',
    appId: '1:579482424180:ios:297e76135357e3264e1221',
    messagingSenderId: '579482424180',
    projectId: 'tfm-control',
    storageBucket: 'tfm-control.appspot.com',
    iosBundleId: 'com.example.tfmControl.RunnerTests',
  );
}
